
services:
  notebook:
    build: ./
    volumes:
      - ./project:/project
      - ./model:/model
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]