
services:

  ollama:
    image: ollama/ollama
    restart: always
    volumes:
      - ./services/ollama/data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
    volumes:
      - ./services/open-webui/data:/app/backend/data

  notebook:
    build: ./services/jupyter/
    restart: always
    volumes:
      - ./services/jupyter/notebook:/project
    depends_on:
      - ollama
    ports:
      - 8888:8888