
services:

  ollama:
    image: ollama/ollama
    ports:
      - "7777:11434"  # Expose Ollama API
    volumes:
      - ./services/ollama/data:/root/.ollama  # Persistent storage for models

  encoder:
    build: ./services/encoder/
    volumes:
      - ./services/encoder/model:/model

  ocr:
    build: ./services/ocr/

  tokenizer:
    build: ./services/tokenizer/

  weaviate:
    image: semitechnologies/weaviate:1.21.2
    restart: always
    depends_on:
      - encoder
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-transformers'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://encoder:80'
    volumes:
      - ./services/weaviate/data:/var/lib/weaviate

  notebook:
    build: ./services/jupyter/
    volumes:
      - ./services/jupyter/notebook:/project
    depends_on:
      - ollama
      - encoder
      - weaviate
      - ocr
      - tokenizer
    ports:
      - 8888:8888

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
    volumes:
      - ./services/open-webui/data:/app/backend/data
