
services:
  llm:
    build: ./services/llm/
    volumes:
      - ./model:/model
    ports:
      - 7777:7777
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  notebook:
    build: ./services/notebook/
    volumes:
      - ./project:/project
    depends_on:
      - llm
    ports:
      - 8888:8888
